name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pip install boto3
          pytest ./cloud-resume/tests/unit/test_handler.py
      - name: Install Dependencies 🔰
        run: npm install

      - name: Run Build 🛠
        run: npm run build
        env:
          CI: false

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://cloudresume.cloud --delete
      - name: Run Playwright Tests
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright install    
          npx playwright test
        

